"""remove_lowlights_add_highlight_percentage

Revision ID: 28f0ebd97beb
Revises: 99aac2a8f948
Create Date: 2026-05-15 11:46:53.717973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f0ebd97beb'
down_revision: Union[str, Sequence[str], None] = '99aac2a8f948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lowlights')
    op.add_column('highlights', sa.Column('percentage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('highlights', 'percentage')
    op.create_table('lowlights',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('kpi_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('order_index', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'not_started'"), nullable=False),
    sa.Column('llm_prompt', sa.TEXT(), nullable=True),
    sa.Column('link', sa.TEXT(), nullable=True),
    sa.Column('image_path', sa.TEXT(), nullable=True),
    sa.Column('video_path', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
