"""add_item_fields_to_highlights_lowlights

Revision ID: 99aac2a8f948
Revises: 5bd337b95c86
Create Date: 2026-05-15 10:49:50.410362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99aac2a8f948'
down_revision: Union[str, Sequence[str], None] = '5bd337b95c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlights', sa.Column('status', sa.String(length=20), nullable=False, server_default='not_started'))
    op.add_column('highlights', sa.Column('llm_prompt', sa.Text(), nullable=True))
    op.add_column('highlights', sa.Column('link', sa.Text(), nullable=True))
    op.add_column('highlights', sa.Column('image_path', sa.Text(), nullable=True))
    op.add_column('highlights', sa.Column('video_path', sa.Text(), nullable=True))
    op.add_column('lowlights', sa.Column('status', sa.String(length=20), nullable=False, server_default='not_started'))
    op.add_column('lowlights', sa.Column('llm_prompt', sa.Text(), nullable=True))
    op.add_column('lowlights', sa.Column('link', sa.Text(), nullable=True))
    op.add_column('lowlights', sa.Column('image_path', sa.Text(), nullable=True))
    op.add_column('lowlights', sa.Column('video_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lowlights', 'video_path')
    op.drop_column('lowlights', 'image_path')
    op.drop_column('lowlights', 'link')
    op.drop_column('lowlights', 'llm_prompt')
    op.drop_column('lowlights', 'status')
    op.drop_column('highlights', 'video_path')
    op.drop_column('highlights', 'image_path')
    op.drop_column('highlights', 'link')
    op.drop_column('highlights', 'llm_prompt')
    op.drop_column('highlights', 'status')
    # ### end Alembic commands ###
